# Metainfo
name: go
env_path: AlphaZero.env.go
game_converter_path: AlphaZero.processing.go.game_converter
state_converter_path: AlphaZero.processing.go.state_converter
gameplay_path: AlphaZero.game.go.gameplay

# Feature parameters for NN input and output
board_width: 19
board_height: 19
history_step: 8
planes_per_step: 2      # Two binary board for each player's stones
additional_planes: 1    # If black is to play

output_plane: 1
flat_move_output: 362


# alpha and epsilon in Dirichlet noise
d_alpha: 0.03
d_epsilon: 0.25

# The transforming function before the NN evaluation.
# Refers to the dihedral reflection and rotation in the paper.
transform_types: 8
