max_playout: 5
pretrained: False

num_blocks: 19                  # number of residual blocks in ResNet
batch_decay: 0.9                # decay factor in batch normalization
learning_rate:                  # learning rate scheme
 0: 1e-2
momentum: 0.9                   # momentum of MomentumOptimizer
l2: 1e-4                        # weight decay factor
MSE_scaling: 0.01               # MSE rescaling factor
save_dir: model/sl
