cluster:
  'curr':
    - 'localhost:3333'
  'chal':
    - 'localhost:3334'
  'best':
    - 'localhost:3335'

datapool:
  pool_size: 5000
  start_data_size: 100
  conn_num: 20

evaluator:
  num_games: 10
  num_worker: 2
  gameplay:
    dirichlet_before: 30
    log_iter: 30
    player:
      max_playout: 5

selfplay:
  num_worker: 2
  gameplay:
    dirichlet_before: 30
    log_iter: 30
    player:
      max_playout: 5

optimizer:
  num_ckpt: 100
  num_steps: 700000
  batch_size: 8
  num_gpu: 1
  num_log: 30
  num_eval: 100
  job: 'curr'
#  load_path:
  log_dir: 'rl/ckpt'
  eval_data_path: 'data/kgs_subset_554_data.hdf5'
  train_val_test:
    - 0.93
    - 0.05
    - 0.02
  eval_batch_size: 64

chal:
  max_batch_size: 32
  num_gpu: 1
  job: 'chal'

best:
  max_batch_size: 32
  num_gpu: 1
  job: 'best'
  load_path: 'sl/3.23/model-127440'