datapool:
  pool_size: 5000
  start_data_size: 100
  conn_num: 20

evaluator:
  num_games: 10
  num_worker: 2

optimizer:
  num_ckpt: 100
  num_steps: 700000
  batch_size: 8

selfplay:
  num_worker: 2

reinforcement:
  chal_max_batch_size: 32
  best_max_batch_size: 32